### ISSUE TITLE
Fix Code Licensing / Attribution Issues

### ISSUE THREAD

**Issue by Daeinar** [dedis/kyber#116]
The following code licensing / attribution problems need to be fixed asap:
- GPLv2 is too restrictive and should be replaced by a more liberal license (e.g. LGPL).
- We need to properly attribute the code that we pulled in from @agl and add the missing license file (see https://github.com/dedis/crypto/commit/1ea738d8d3907106db28f4f4deba99a4274ac561). The rest of the code base should be checked for similar issues.

**Comment by theckman** [comment]
Might you consider the same permissive approach as the Go language itself (BSD 3-Clause style license)?

**Comment by Daeinar** [comment]
@theckman Unfortunately, the discussion around this issue got stuck a while ago so there is no conclusion yet. I'll add your proposal to make sure that we don't forget it.

**Comment by theckman** [comment]
@Daeinar No worries. Licensing is always a PITA. 😄  I do appreciate you taking my comment down for consideration.

Cheers!

**Comment by ineiti** [comment]
Discussing with Bryan we decided to go with an LGPL-license for the code, and also adding the appropriate licenses for the other parts of the code.

The main reason being that we believe in Open-Source collaboration and would like to have people participate in the coding-effort if they use our library.

**Comment by theckman** [comment]
@ineiti Unless I misunderstood the LGPL, this means anyone consuming this library will need to release full source code as Golang is statically linked WRT dependencies. Not everything I work on can be open sourced, but I'll happily provide changes upstream. By choosing this license I'm afraid I won't be able to use the library and inherently would be unable to provide my own fixes for you to review.

I do ask that you please reconsider as I firmly believe your decision may have the Inverse impact on this project.

**Comment by ineiti** [comment]
@theckman what you describe is the GPL. With the LGPL this requirement is removed: http://www.webopedia.com/TERM/L/LGPL.html - so you're welcome to include the code even in proprietary code. But if you change our library, you have to publish those changes.

Does that clear it up?

**Comment by ineiti** [comment]
So my previous comment obviously misses the obvious, sorry. I let it there anyway and correct myself here. I was not aware of the problem of statically linking that happens with golang. Of course this is not what we want to do, and so we need to reconsider our use of LGPL. 

Doing a short search points out the Mozilla Public License would be between the LGPL and the Golang-license. Would the MPL be suitable for you?

**Comment by theckman** [comment]
MPL or Apache 2.0 would absolutely work. Thank you for having this discussion and being open to feedback about the licensing choice of this project.

**Comment by Daeinar** [comment]
@theckman Thanks for your feedback, that's good to know. We'll schedule another discussion internally about that as soon as possible to get that finally fixed.

**Comment by ineiti** [comment]
OK, fixed the PRs.

**Comment by Daeinar** [comment]
@ineiti: Thx!

As a summary: We've decided to go for MPL v2.0. (/cc @theckman)
