### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by ineiti** [dedis/kyber#153]
There are a lot of branches in kyber - which ones are needed?

**Comment by nikkolasg** [comment]
I have cleaned most branches I know I can safely delete. We're gonna have to see with @Daeinar for some branches...
Does it really belong to v1 ? I think it's a general issue "to do anyway". (I'm trying to finish that epic asap ;) )

**Comment by ineiti** [comment]
Only the following are left:
```
randhoundco 
randherd
randhound
```

**Comment by ineiti** [comment]
Done
