### ISSUE TITLE
Go-wishlist

### ISSUE THREAD

**Issue by ineiti** [dedis/kyber#154]
Go through go-wishlist and put things needed into issues and remove go-wishlist-file.

**Comment by nikkolasg** [comment]
It's more about things @bford implemented himself because Golang did not provide it by default. So these issues do not really belong as issues in our crypto library. I'd either keep the file as is or delete it.

**Comment by ineiti** [comment]
Kill it in `v1`. We can leave it in `v0`.

**Comment by nikkolasg** [comment]
Done in https://github.com/dedis/kyber/commit/a1705b19d596d40e8e8c5ed66d9dfd099d9e36dd
