### ISSUE TITLE
Use coveralls.sh

### ISSUE THREAD

**Issue by ineiti** [dedis/kyber#156]
I propose we switch to use of coveralls.sh like in onet and cothority. Then cry and write tests ;)

**Comment by nikkolasg** [comment]
We don't need coveralls.sh. Coverall is already used in kyber, see https://coveralls.io/github/dedis/kyber .
Although, I can't access the "settings" page for this repo ( I can with Onet). But our latests PR already include the test coverage, and it's always increasing so we see no warnings.

**Comment by ineiti** [comment]
Oups - 46%...
