### ISSUE TITLE
test-directory

### ISSUE THREAD

**Issue by ineiti** [dedis/kyber#159]
Is this the best way to go to have a main `test`-directory?

- it won't work nice with `coverage`
- you cannot run `go test` in the subdirectories and look if you broke something
- the tests are dissociated from the code (which might be OK for integration-tests, but IIRC, these are unit-tests).

**Comment by nikkolasg** [comment]
The `test` directory provides a common way to test new `Cipher` and `Suite` or `Group` implementations. 
One way to remove that would be to make the test package method take a `t *testing.T` argument so one could call the whole test methods just by one call in `mysuite_test.go`.
What do you think ?

**Comment by ineiti** [comment]
Yes, that sounds better. Would it make sense to put the test into `util`?

**Comment by nikkolasg** [comment]
Definitely. I'll work on that to see if it makes sense.

**Comment by nikkolasg** [comment]
In fact, it's already the way it works, each suite just call `test.TestSuite(suite)` without giving the `testing.T` argument. I've just moved `test/`to `util/test` for the moment, I think it's sufficient. If we want later, we can make the `test/` package build only for the testing (so not in any release binary) by putting everything in `*_test.go` files but I think it's not that urgent ;)
