### ISSUE TITLE
schnorr-signature

### ISSUE THREAD

**Issue by ineiti** [dedis/kyber#160]
I liked the way we had the students write schnorr-signatures with structures revealing the challenge and response - why is it now a `byte`-only method?

**Comment by nikkolasg** [comment]
We already had that discussion a while back. 
In short, because 
1) one should not need to dissect a signature, it should be used as an opaque / black box thing where you can't potentially screw up (is R or s encoded before etc)
2) it's compatible with EdDSA and CoSi verification routines.

**Comment by nikkolasg** [comment]
I think we can close this issue for now. If _needed_ , I can provide a small wrapper to a structure later in this package easily.
