### ISSUE TITLE
Example-directory

### ISSUE THREAD

**Issue by ineiti** [dedis/kyber#162]
That looks strange for a number of reasons:

- `ds_test.go` seems it should be in the new *SS-packages, and all is commented out
- `enc_test.go` is an el-gamal encryption - should that not be placed somewhere else? Looks useful
- `sig_test.go` another schnorr?

I'd remove the `example`-directory and add the el-gamal somewhere else.

**Comment by nikkolasg** [comment]
`sig_test` is the signature example, for higher level example than just the tests themselves. 
`ds_test` relies on the *old* sharing code, the one in `poly/` so it has to be re-made. I'll make an issue.
`enc_test` is also an example, and not a test. 
Before those files were at the top level, and it's not really possible anymore (circular injection otherwise). I thought using a `example` folder would be the ideal solution instead splitting out examples everywhere in our code (where each package already contains plenty of `*_test.go`.)
Where would you put that ?

**Comment by nikkolasg** [comment]
@ineiti Do you have any comments on that ? Otherwise, it's a good-to-close issue.

**Comment by ineiti** [comment]
Hmm, don't close it just yet. What's your proposed action?
* ds_test.go - remove
* enc_test.go - create as real module, ElGamal encryption is useful
* sig_test.go - remove, we already have Schnorr

Examples are OK, but I would not put things like ElGamal, which is useful, in an example-directory. Rather I'd put an example how to use ElGamal in that directory.

**Comment by nikkolasg** [comment]
Where would you put `ElGamal` ? We don't have any `ElGamal` package. Would we have one, I'd be ok to move the example into that package.
And why moving out a file from the `example/` folder on the basis it is "useful" ? Is it not good that our examples **are** useful ? ;)
It's not that important but I see that @bford already had an opinion on it on an old [issue](https://github.com/dedis/kyber/issues/10) which lies closely to the current organization.

**Comment by ineiti** [comment]
My first thought was to put it into the `cipher`-directory, but ElGamal is no cipher-encryption.

I mean, kyber is a crypto-library, so probably people will want to use ElGamal-encryption. And if they have to `import` the example-directory, that looks a bit strange. So yes, useful examples are nice, but useful things should be in the library, no?

**Comment by nikkolasg** [comment]
> if they have to import the example-directory

They don't import the example directory, they look at it and reproduce it, as what an example is meant for. The best thing would be to have a ElGamal package, but it's not our priorities right now...

**Comment by ineiti** [comment]
s/priorities/priority/

OK, as we don't have a good non-cipher encryption directory yet, let's keep it at that.

**Comment by ineiti** [comment]
We could

1. put it into a `/keyenc`-folder
2. add a `/encrypt`-folder, move the `/cipher`-folder in there and add a `/encrypt/elgamal`-folder

**Comment by jeffallen** [comment]
The example directory is getting final checks in #152.
