### ISSUE TITLE
[CoSi] API improvements

### ISSUE THREAD

**Issue by nikkolasg** [dedis/kyber#169]
Now that CoSi is getting used, there seems to be API improvements possible on the CoSi codebase. @ineiti and @Daeinar please list up your wishes in this issue ;)

**Comment by ineiti** [comment]
I would like to have a basic `struct` like for `SchnorrSig` that holds just the necessary variables and methods to use CoSi.

The protocol should be based on that struct.

The struct should also help in writing tests when you want to set up some CoSis. (can't find the test I wrote anymore :(

**Comment by nikkolasg** [comment]
Like 
```go
type CoSiSig struct {
  Challenge Scalar
  Response Scalar
  AggCommitment Point
}
```
Stg like that ? In what ways would it help ? 
It'd be nice if you can find your tests or your changes on CoSi again, so we can discuss on the code, I have trouble to see what are the benefits here.

**Comment by ineiti** [comment]
The current implementation in the `kyber`-repo is already very much geared towards the actual protocol. What I needed the other day was a way to use CoSi outside of the protocol itself. And the current code was too _protocolified_ to be used.

**Comment by nikkolasg** [comment]
I understand the concept of what you *mean*, but I have hard time getting to an exact idea of what you *want*. CoSi **is a protocol**. The cryptograhic signature itself is a simple schnorr signature otherwise.
I'm sure your code is lying around somewhere.. or maybe you could do a draft by remembering it ?

**Comment by ineiti** [comment]
The code in itself is not really relevant. All it does, as you say, is to apply a collective Schnorr-signature on some data. As such it's not very interesting.

But: is `kyber` the place to implement a protocol? Shouldn't `kyber` give the basic implementation, even if it is 'just' a simple Schnorr signature? And then have the more protocol-based parts in `cothority` or so?

I don't think it has high priority for the moment. But it's worth thinking about it.

**Comment by bford** [comment]
Remember my super-simple Go "crypto-only" (no-protocol) implementation of CoSi signing, which is lying around somewhere (can't remember exactly where)?  That might be a good example of a chunk of code that might arguably belong in kyber.  CoSi signature verification at least does not and should not have any "protocol" to it at all.  And it's certainly possible to formulate a simple crypto-only set of primitives to compose CoSi signatures without bringing all the protocol stuff into it.  Perhaps that's the kind of thing Linus is suggesting, and I would in general support the idea of decomposing the "bare crypto" part of CoSi (primitives for creating and checking CoSi signatures) from the "protocol" part of CoSi.  There might in principle be many other reasonable ways of creating CoSi signatures than using the (current) CoSi protocol.

**Comment by nikkolasg** [comment]
Again, I understand what you mean but not the practicalities. What is the protocol parts that are present in the current code that you wish to separate ? https://github.com/dedis/kyber/blob/master/cosi/cosi.go
Looking back at the code, there may be some naming issues that suggests the use of a Tree for example but this package is agnostic to the protocol / transport layer. 
The protocol only asks for the cryptographic material in each steps, but it does require an "ordering" in the calls: `Challenge` must be called before `Response`.
One way I can think of changing cosi so it's even more agnostic to the "steps/protocol" is to give everything in parameters. Example: 
+ `CreateChallenge` could be a public function which takes an commitment, a public key and a message. 
+ `CreateResponse` could be a public function taking a challenge, a private key, and a private commitment.
Does that sound more in the line of what you both wish ?

**Comment by Daeinar** [comment]
Hi all,

While writing the policy mechanism for CoSi, I bumped into several problems / inconsistencies with the current CoSi implementation and then realised that there is already an issue on the simplification of the CoSi API. I've briefly sketched a bare bones (crypto-only) CoSi implementation that gets rid of the current CoSi struct in the following pull request (see the file `cosi_new.go`): https://github.com/dedis/kyber/pull/188

Feedback welcome. Thanks!
