### ISSUE TITLE
[v1] Delete `group.PointLen()` and `group.ScalarLen()`

### ISSUE THREAD

**Issue by nikkolasg** [dedis/kyber#187]
Should we delete `group.PointLen()` and `group.ScalarLen()` from the `Group` interface ?
The question is asked in a XXX in https://github.com/dedis/kyber/blob/v1/group.go#L166

**Comment by ineiti** [comment]
I just used them to make the CoSi and BFTCoSi more general and allow for non-ec25519 groups. Personally I prefer

`suite.PointLen()`
over
`suite.Point().Length()`

as the latter has to instantiate a point that will be thrown away. But it's not tragical if you think the interfaces look really, really nicer like that ;)

**Comment by nikkolasg** [comment]
Ok I think it's fine too to keep them since as you stated, it's much more cleaner that way. Just wanted to raise the point...
Anyway, I'll think this kind of properties will be moved down to a more general "properties struct" or stg but that's yet another story.
