### ISSUE TITLE
[API] Simplify proof/proof.go API

### ISSUE THREAD

**Issue by nikkolasg** [dedis/kyber#192]
In `proof/proof.go`, a comment raises the issues if the interface for `Predicate` should be simplifed or not, maybe using reflection. 
While I'm all for simplifying APIs, I'm not so much in favor of using reflection when it can be avoided. 
We should dedicate some thoughts to this issue.

**Comment by ineiti** [comment]
I would not put too much `reflect`ion in `kyber`. For `onet` it's OK to have some automatisms, but for a low-level library I'd make it as straightforward as possible. Can you add a link to the line in question?

**Comment by nikkolasg** [comment]
https://github.com/dedis/kyber/blob/master/proof/proof.go#L14

**Comment by jeffallen** [comment]
Proof has just been marked experimental, and is not used anywhere, so frther tinkering with it is not worthwhile.
