### ISSUE TITLE
Migration Plan for v1

### ISSUE THREAD

**Issue by nikkolasg** [dedis/kyber#199]
Here we are, approaching the date when we can finalize & conclude for the v1 release. 

Unfortunatly, the way we have done that is quite troublesome, since we started from the v1 branch directly, and not on master. Since the master branch also evolved during the meantime, it's important have a clear strategy on how do we want to proceed. 

The general idea is that, at the end, we want the v1 branch to be on master too, so we can continue developing on master while having a stable v1 branch. 

We need to list up all the things that have changed in master but not in v1. From what I recall I only see the current CoSi changes that @Daeinar is doing.
Do any of you coded stg on the master branch ? 

So the plan would be to:
+ port the cosi's changes to v1
+ push v1 to master
+ make announcement

**Comment by ineiti** [comment]
Sounds good. For further development, we'll use the `master`-branch. Also for `onet` and `cothority`. So `master` and `v1`/`v2` will be out of sync, and only important things will be ported back to `v1`/`v2`.

**Comment by ineiti** [comment]
Changed issue with three issues into three issues.
