### ISSUE TITLE
Make announcement for v1

### ISSUE THREAD

**Issue by ineiti** [dedis/kyber#209]
We (@bryan?) have to write an announcement for the world to know that `kyber.v1` is out and is going to rock the world!

**Comment by nikkolasg** [comment]
Here was my tentative email from when we thought we were ready as young crypto-padawans (sorry for the weird formatting, thunderbird seems not compatible with github MD :D):

> Hi,
> 
> Today, we are excited to share with you the newest release v1 of our
> cryptographic
> library Kyber !
> We have worked hard to provide a much more reduced, tighter and better
> organized
> code base with additional exciting features such as distributed key
> generation
> protocols or discrete logarithm equality proofs.
> You can checkout the library using `go get -u gopkg.in/dedis/kyber.v1` and
> read the documentation at http://godoc.org/gopkg.in/dedis/kyber.v1.
> 
> Here are some of the highlights of this v1 release:
> 
> + Many of the primitive interfaces of kyber moved from the `abstract/`
> package to
> the top root level of the kyber library. One now just need to import the
> `gopkg.in/dedis/kyber.v1` to start using `kyber.Group`, `kyber.Scalar` and
> `kyber.Point` amongst other.
> 
> + The poly/ package has been re-created from scratch and is now contained in
> share/. This features secret and public polynomial arithmetics, verifiable
> secret sharing, distributed key generation and threshold distributed schnorr
> signatures.
> 
> + Groups implementing variable time arithmetics are only available using the
> "vartime" compilation tag: `go build -tags vartime`. Currently, only
> the edwards25519 group is available by default.
> 
> + Lots of packages have been removed from this version since they are
> not used
> nor maintained anymore. We've been able to delete up to a dozen of
> folders and
> files such as openssl, poly, base64 etc.  Also, all utility functions moved
> into a util/ folder into their own subfolder. For example, now one must
> import
> `util/subtle` to use the dedis `subtle` package.
> 
> + Removal of the global Suite interface definition. Now each package must
> define their functionalities that they need in order to function
> properly. For
> example, the vss package defines its own Suite:
> ```go
>       // Suite defines the capabilities required by the vss package.
>       type Suite interface {
>           kyber.Group
>           kyber.CipherFactory
>           kyber.HashFactory
>       }
> ```
> 
> + The one backward-compatibility breaking change we made is to switch the
> order of the arguments in `Point.Mul()`: the scalar must now be the first
> argument, and the point the second.
> 
> + Many small improvements and bug fixes.
> 
> You can check the CHANGELOG to have an exhaustive description of all
> changes.
> We hope you will enjoy this new release, and we are welcoming any feedback !
>

**Comment by ineiti** [comment]
Thanks - I put it into our internal google-docs under `DEDIS/Coding`

**Comment by jeffallen** [comment]
There is a proposed blog posting here: https://github.com/dedis/dedis-ch-website/pull/2
When kyber,onet,cothority v2 are released, that blog posting should be updated and then published.
