### ISSUE TITLE
DistKeyGenerator needs Marshal/Unmarshal methods

### ISSUE THREAD

**Issue by ineiti** [dedis/kyber#217]
For use in `service`s, `DistKeyGenerator` needs to be able to stored and loaded on disk, so Marshal/Unmarshal is needed.

**Comment by ineiti** [comment]
Too complicated to use the full DKG - I'll just gonna get the values I want and store them separately in the service.

**Comment by nikkolasg** [comment]
You should not need to store the full DKG, only the `DistKeyShare` structure (the distributed key)  is needed. Once the DKG is done, you can throw out the `DistKeyGenerator`.

**Comment by ineiti** [comment]
OK, makes sense. In the end I made my own structure with `V`, `I` and `X` inside.
