### ISSUE TITLE
[vss] dkg / vss synchronous settings problem

### ISSUE THREAD

**Issue by nikkolasg** [dedis/kyber#219]
The original design for Rabin or Pedersen vss/dkg is synchronous settings, that means it works in round, where at each round a message is delivered or not.
In both DKG protocols, they consider the absence of a message as a "acknowledgement" of a correct deal. At the end of the protocol, each node has the same set of correct deals.
Since we don't work in these settings, I took the liberty to use a `Response` message that explicitely gives an acknowledgement or a complaint about a deal. 
Unfortunately this can bring confusion: two participating nodes may end up with different public polynomial at the end of the protocol, if they did not take the same set of correct Deals because **they only need > t deals** and don't know if they should wait for another valid deal or not (because we work in an asynchronous setting)..
DKG in asynchronous settings seems not there yet but there are promising papers we should look at to alleviate that assumptions.
For the moment, every deal should be either acknowledged or refused.
The library currently is not doing that check but I'm not sure it should because that means that it's impossible to have one node offline (i.e. out of the dkg) during the dkg...
**EDIT**: I'm doing that check in my local version in https://github.com/dedis/paper_17_dfinity

**Comment by K1li4nL** [comment]
Hello and thank you for bringing up this issue, after some discussion with the rest of the team, we decided to close it for the following reasons:

The handling of churns and timeouts doesn't necessarily belong in kyber but to upper layers (e.g networking). And async DKGs would require new implementations which are not a priority at the moment but could be added after we release the v4. Thank you again !
