### ISSUE TITLE
Pass master-build

### ISSUE THREAD

**Issue by ineiti** [dedis/kyber#221]
For the moment the build in master doesn't pass because of the `experimental`-branch. I started to add a `experimantal/abstract` to write a small _wrapper_ for the old `v0`-interfaces, but gave up when being confronted with `Hiding` and `Cipher`...

The other, more simple solution, is to ignore `experimental` when testing with travis.

**Comment by Daeinar** [comment]
I would say that we ignore the experimental folder in travis for the moment and check that everything else passes.

**Comment by ineiti** [comment]
Second that - but then we need to add our `coveralls.sh`-script, because `goveralls` does a `go test ./...` on the repository, and if `experimental` doesn't build, it fails...

So we can either
a. add `coveralls.sh` and give `experimental` as repo not to test
b. fix `experimental` so that it builds at least

**Comment by ineiti** [comment]
or c. add `+build experimental` to the `experimental`-directory - which looks to be the best.

Just in case somebody else wants to do that: be sure to have an empty line after the `// +build experimental` line, else golang doesn't recognize it :(

**Comment by Daeinar** [comment]
Agreed, option c) seems straightforward and rather simple to realise. Lets use that for now.
