### ISSUE TITLE
public APIs should not panic

### ISSUE THREAD

**Issue by jeffallen** [dedis/kyber#239]
group.Suite() can call panic.

Public APIs should not do that. They should return errors.

**Comment by jeffallen** [comment]
This issue was opened for group.Suite() but it covers auditing all calls to panic in kyber.

**Comment by bford** [comment]
Can you clarify what you mean by "public API"?  Certainly any API that is accessible *remotely* from another node (e.g., via protobuf/RPC) should never panic but only gracefully produce errors if it receives invalid arguments and such.  

But when you're talking about APIs used only within a process (public to a Go package but still internal to the larger Go program), and the function detects that it was called or used in a way that correct code should never ever have legitimate reason to call or use it (invalid arguments, etc) - i.e., something that definitely points to a software bug in this same process - then I think panic may well be better.  This is of course a debatable point, but the benefit of using panic in that context is it guarantees the bug will be detected immediately if it actually occurs, whereas error codes always present a rather non-trivial risk that the caller will forget to check them or do anything useful or detectable with them.

**Comment by jeffallen** [comment]
From [Effective Go](https://golang.org/doc/effective_go.html#panic):

"real library functions should avoid panic. If the problem can be masked or worked around, it's always better to let things continue to run rather than taking down the whole program. One possible counterexample is during initialization: if the library truly cannot set itself up, it might be reasonable to panic, so to speak."

**Comment by jeffallen** [comment]
group.Suite(string) could be reasonably expected to be passed user input, i.e. from a config file or an environment variable. So it must return an error, not panic.

**Comment by bford** [comment]
Yes, in any case involving user input (string parsing, looking up ciphersuites by name that might not exist in this build, etc), for sure a graceful error rather than panic is most appropriate.  But for situations where the caller has immediately violated a basic contract invariant of the API, I still think panic is more appropriate.  For example, passing a null pointer or a slice that's too short for what the callee is supposed to do with it...
