### ISSUE TITLE
simplify build system

### ISSUE THREAD

**Issue by jeffallen** [dedis/kyber#256]
We need to try building for all build tags (vartime, experimental)

Adding that with the current Makefile based system is difficult, because the "test" target is not defined in the same repo as the build tags (see https://github.com/dedis/Coding/blob/master/bin/Makefile.base#L52)

We need to find out if we can simplify things so that .travis.yaml is the only file you need to edit to explain how to build and test the system.

**Comment by nikkolasg** [comment]
> We need to find out if we can simplify things so that .travis.yaml is the only file you need to edit to explain how to build and test the system.

+100 for that, I think we don't really need a makefile here.

It is possible to pass build flags to go test IIRC so that should be possible to test all the code just using .travis.yaml I believe.

**Comment by ineiti** [comment]
There is no `experimental` anymore.

**Comment by pierluca** [comment]
I believe this has been done. I'm closing the issue.
Feel free to re-open if you still feel it's an issue.
Thanks.
