### ISSUE TITLE
remove random.Stream

### ISSUE THREAD

**Issue by jeffallen** [dedis/kyber#257]
...and make the heavy API changes necessary so that all places it was used can specify a seeded RNG if they need stability during testing.

See #253 for the hacky way we make this possible today, that we want to remove for v1, hopefully.

**Comment by ineiti** [comment]
Thinking out loud: this means that all signing/encrypting methods will need to take a `random-Stream` as input parameter, so that tests can give a 'static' random for reproducible tests.

**Comment by jeffallen** [comment]
Yes, unless you add the "current random stream" to the suite. Which would be sweet, but my first experiments with it were fragile and would have further increased the burden of explaining the Suite system to new programmers. So I am taking the more conservative, idiomatic Go approach.

**Comment by nikkolasg** [comment]
Sorry I did not follow through but the `random.Stream` object is quite useful to generate truely random keys to use in production, and not in testing. How would we achieve that now ?
