### ISSUE TITLE
remove support for base64

### ISSUE THREAD

**Issue by jeffallen** [dedis/kyber#267]
The points and scalars that we typically work with are small enough that they are manageable in hex format (for ed25519, 32 bytes -> 64 characters).

We have seen some bugs already from confusion of which format belongs in which place.

This issue is to gather opinions about removing base64 encoding entirely from kyber, in order to encourage/require cothority and cothority-derived apps to use hex only.

**Comment by jeffallen** [comment]
Need votes, please: @bford @ineiti @nikkolasg 

String64 occurs in these places right now in cothority:

```
./pop/app.go:		pub, err := encoding.String64ToPoint(cothority.Suite, k)
./pop/app.go:	secStr, err := encoding.ScalarToString64(nil, kp.Secret)
./pop/app.go:	pubStr, err := encoding.PointToString64(nil, kp.Public)
./pop/app.go:	public, err := encoding.String64ToPoint(suite, s.Public)
./pop/service/api.go:		pub, err := encoding.String64ToPoint(cothority.Suite, p)
./pop/service/api.go:		pub, err := encoding.String64ToPoint(cothority.Suite, s[3])
./pop/service/api.go:			pub, err := encoding.String64ToPoint(cothority.Suite, s[3])
./pop/service/api.go:		str, err := encoding.PointToString64(nil, p)
./pop/service/api.go:		str, err := encoding.PointToString64(nil, si.Public)
./pop/service/api.go:	token.Private, err = encoding.String64ToScalar(cothority.Suite, t.Private)
./pop/service/api.go:	token.Public, err = encoding.String64ToPoint(cothority.Suite, t.Public)
./cisc/cisc.go:		pub, err := encoding.String64ToPoint(cothority.Suite, k)
./cisc/cisc.go:	secStr, err := encoding.ScalarToString64(nil, kp.Secret)
./cisc/cisc.go:	pubStr, err := encoding.PointToString64(nil, kp.Public)
./cisc/cisc.go:		kp.Secret, err = encoding.String64ToScalar(cothority.Suite, priv)
```

So practically, this is a proposal to convert POP and CISC into hex-only apps.

String64 is not in onet at all at this point.

**Comment by nikkolasg** [comment]
I'm in favor of keeping only one encoding format. Which one is another question.I don't have strong preferences but maybe there are some criterias that could help ?
Anyway, count my vote where you need it the most, I'm fine with it ;)

**Comment by ineiti** [comment]
base64: shorter (6bit/character instead of 4bit/character)
base58: used by some wallets in Bitcoin (better differntiation of O/0 and others)
hex: used by Ethereum, easier debugging when comparing points and scalars

As I'm mostly debugging, I'm in favour of hex-encoding ;) But user-wise it could be better to use base64.

We could say that hashes are in base64, and points/scalars in hex. But that's also mixing.

Let's just go all-hex.

**Comment by jeffallen** [comment]
I also vote for hex only (in kyber; users of kyber with special needs like a Bitcoin-compatbile something could still use base58, of course).

So that's 3 votes for hex only, and Bryan is busy cleaning his house. I'll implement hex only today.
