### ISSUE TITLE
SetBytes endianess should be better documented

### ISSUE THREAD

**Issue by jeffallen** [dedis/kyber#275]
This was first reported by @ecnerwala in PR #274.

After a lot of consideration and prototyping other fixes, we've decided it is ok for this to stay implementation-defined.

**Comment by ecnerwala** [comment]
Alright, you guys are the maintainers, so you guys have the final say, but what does it even mean for a *setter* and not the associated getter to be implementation dependent? How are you supposed to know what to pass in?
