### ISSUE TITLE
[pairing] point.go: parameters inversion in sub()  

### ISSUE THREAD

**Issue by froelich** [dedis/kyber#287]
In the pairing branch, in file "point.go", the parameters for the sub() function are inverted. I think this is the case for pointG1, pointG2 and pointGT.
For pointG1, I think the this:
`func (p *pointG1) Sub(a, b kyber.Point) kyber.Point {
	x := a.(*pointG1).g
	y := b.(*pointG1).g
	p.g.Neg(x)      // p = -b
	p.g.Add(p.g, y) // p = p + a = -b + a
	return p
}`

should be:

`func (p *pointG1) Sub(a, b kyber.Point) kyber.Point {
	x := a.(*pointG1).g
	y := b.(*pointG1).g
	p.g.Neg(y)      // p = -b
	p.g.Add(p.g, x) // p = p + a = -b + a
	return p
}`

**Comment by Daeinar** [comment]
@froelich Thanks for reporting. I found that very same bug while writing some tests. ;) It's fixed now.
