### ISSUE TITLE
[ed25519/eddsa] Malleable signature

### ISSUE THREAD

**Issue by nikkolasg** [dedis/kyber#311]
We should enforce that the ed25519 and eddsa packages enforce non-malleability of the signatures.
See agl's [commit]( https://github.com/golang/crypto/commit/c4a91bd4f524f10d064139674cf55852e055ad01) for example. 
Unfortunately, it is not straightforward to do that at the current state of the code, because we currently don't have a way to get the field order (to check if the scalar is in the range `[0,order[`).
See https://github.com/dedis/kyber/issues/259 for a related issue.

**Comment by jeffallen** [comment]
@Daeinar could you please comment on this? To me it seems like a nice-to-have, but not critical before v3 (because it is not a backwards incompatible change)

**Comment by calctopian** [comment]
Superseded by issue #426 and solved by PR #427.
