### ISSUE TITLE
pairing/bn256 G2 marshal

### ISSUE THREAD

**Issue by PizzaWhisperer** [dedis/kyber#321]
Using an extra bit to deal with the case of infinity point doesn't provide compatibility with the google bn256 library.
We see here : https://github.com/dedis/kyber/blob/master/pairing/bn256/point.go#L365, that the final marshal size is not compatible with what is required here : https://github.com/golang/crypto/blob/master/bn256/bn256.go#L241. 
To restore compatibility we could get rit of the bit ret[0] which is set manually (https://github.com/dedis/kyber/blob/master/pairing/bn256/point.go#L292) for something inspired by https://github.com/golang/crypto/blob/master/bn256/bn256.go#L254.

**Comment by PizzaWhisperer** [comment]
We see here : https://github.com/dedis/kyber/blob/master/pairing/bn256/point.go#L365, that the final marshal size is not compatible with what is required here : https://github.com/golang/crypto/blob/master/bn256/bn256.go#L241.

**Comment by nikkolasg** [comment]
I've had a quick look and here are my findings. They may be redundant as to what @PizzaWhisperer mentionned above, but I wanted to make out a clear picture of the issue first:
- In kyber, we use this extra byte to determine if the point is at infinity or not 
```go
if len(buf) > 0 && buf[0] == 0x00 {
    p.g.SetInfinity()
```
If it is set to `0x01`, it is a "regular" point.
- in crypto, they determine this information simply from the points themselves:
```go
if e.p.x.x.Sign() == 0 &&
	e.p.x.y.Sign() == 0 &&
	e.p.y.x.Sign() == 0 &&
	e.p.y.y.Sign() == 0 {
	// This is the point at infinity.
	e.p.y.SetOne()
	e.p.z.SetZero()
        e.p.t.SetZero()
```
The reason of determining the infiniti-ness that way is unknown from me, if it's important we can ask https://github.com/Bren2010 later on.
So I support @PizzaWhisperer 's proposed change to remove that extra byte and test if the point is at infinity the same way Go does.
