### ISSUE TITLE
[edwards25519] NewKey related (potential) issue

### ISSUE THREAD

**Issue by sarkortrantor** [dedis/kyber#351]
NewKey (part of key generator interface) generates secrets of the correct form
(lying in 2^254 + 8{0,1,2,...,2^251-1}) before calling scalar.SetBytes to retrieve the scalar.
However SetBytes reduces modulo q (order of subgroup generated by base point (9,)).
Since q=2^252+... < 2^254 IMHO we just destroy what we have done.
(or if turns out that deeper understanding shows this is not an issue, deserve some documentation)

**Comment by sarkortrantor** [comment]
original discussion with @Daeinar :

Lucas Pires [12:44 PM]
Hi,
I spotted a strange thing in kyber and don't want to start an issue and potentially long discussion on github (i'm short in time and confidence in myself ^^)

Lucas Pires [12:53 PM]
specifically, edwards25519/curve.go implements the key generator interface, the intended goal of implementing it is to generate DH keys that works well in curve25519 crypto, i.e. set the scalar secrets to a multiple of 8 (to avoid/mitigate small subgroup attacks (Lee-Lim) without having to check point in correct order subgroup and force bit 254 to 1 to mitigate another problem with some implementations (time leaks etc..)

fine,
but right after having correctly tweaked the bits our implementation calls setBytes which internally reduce mod q (the prime order of subgroup).
which will cancel any correction we made
(q = 2^252 + ..... < 2^254) (edited) 
I wanted to have your thoughts on that

daeinar [12:58 PM]
Hi Lucas. Good question, to which I have no answer at the moment. Did you check other reference implementations (in Go or other languages) how they are handling this case?

Lucas Pires [1:10 PM]
not checked but according to original bernstein paper proper secret keys are in 2^254 + 8 {0,1,2...2^251-1}
https://cr.yp.to/ecdh/curve25519-20060209.pdf
(note that in this paper Curve25519 is the DH function i.e. X25519)
apparently
https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_sign/ed25519/ref10/keypair.c
just stop at the bittwiddling (note that now the keys are for EdDSA not DH but we don't care, the modificaiton of the bits are to prevent attacks that apply to both..)
in my understanding it means that concretely/accidentally current implementation in kyber don't care about the advice
(while giving the impression it does => bad)

daeinar [1:14 PM]
https://github.com/dedis/kyber/blob/master/group/edwards25519/curve.go#L58
that’s the problematic line you’re worried about, right?

Lucas Pires [1:15 PM]
yes
or said differently the implementation of setbytes that reduce mod q


daeinar [1:16 PM]
this here https://github.com/dedis/kyber/blob/master/group/edwards25519/scalar.go#L143

Lucas Pires [1:16 PM]
yes

daeinar [1:17 PM]
hmmm
Might be worth checking out what https://github.com/dalek-cryptography/curve25519-dalek and https://github.com/agl/ed25519 are doing
but I think you are right that this could be a problem

Lucas Pires [1:22 PM]
as a quick concrete example the "random as xkcd" secret 2^254+8 when reduced mod q is no longer a multiple of 8

daeinar [1:22 PM]
yup

**Comment by nikkolasg** [comment]
I think you're right as well - even though in the good "range", the resulting scalar may not be a multiple of 8 hence the subgroup attack may happen nonetheless.
Back at the time, there was some discussion about whether to modulo or not at the time, when we introduced this `SetBytes` but there were some disagreements (what are the exact semantical differences between `UnmarshalBinary` and `SetBytes` ...)
Seems like a quick fix could be to not use `SetBytes` in the `NewKey` method, and simply to copy to the buffer `s.v`, since it's in the same package (or  use `UnmarshalBinary` but then we should remove the `SetBytes` in my opinion).

**Comment by sarkortrantor** [comment]
> even though in the good "range", the resulting scalar may not be a multiple of 8 hence the subgroup attack may happen nonetheless.

out of curiosity, can you elaborate on this ?
to my current understanding all correct secrets are multiple of 8 in [2^254;2^255[
(it is one of the point of the bit twiddling, to prevent an attacker gaining any knowledge out of sP (i.e. s mod 8) where P has order 8 and s is the secret)

**Comment by kc1212** [comment]
It seems the fix for this issue won't break API because it's a matter of changing how keys are generated but the byte-representation won't change. Will look at it after v3.
