### ISSUE TITLE
Using signature.UnmarshalBinary to convert from string

### ISSUE THREAD

**Issue by steamonimo** [dedis/kyber#358]
I have a valid signature as a string. The conversion from string to binary via signature.UnmarshalBinary only works if the members R (Point) and S (Scalar) of the signature are properly initialized as follows. Otherwise the code fails with "panic: runtime error: invalid memory address or nil pointer dereference":
```
signatureBytes, _ := hex.DecodeString("put signature string here")
signature := schnorr.Signature{}
// important initialization
signature.R = curve.Point().Base()
signature.S = curve.Scalar().Zero()
signature.UnmarshalBinary(signatureBytes)
```
I would like to propose that the method signature.UnmarshallBinary should recognize that R and S must be initialized and will do so internally. This way the following would work without panic error:
```
signatureBytes, _ := hex.DecodeString("put signature string here")
signature := schnorr.Signature{}
signature.UnmarshalBinary(signatureBytes)
```

**Comment by jeffallen** [comment]
Which version of Kyber are you using (what import path)?

**Comment by steamonimo** [comment]
It is V2.

I am using the following import paths:
"gopkg.in/dedis/kyber.v2"
"gopkg.in/dedis/kyber.v2/group/edwards25519"
