### ISSUE TITLE
add TextMarshaller

### ISSUE THREAD

**Issue by jeffallen** [dedis/kyber#360]
Comment seen in wallet code on cothority.
```
// All these structures are used to save/load json files. This is due to the
// fact that points and scalars are not storable in json. An alternative would
// be to add `TextMarshaller` to Point, Scalar and the IDs.
```

That's a good idea, let's do it.

**Comment by K1li4nL** [comment]
Hello, thank you for the request, we decided not to implement it, with the marshallers already implemented it is rather straight forward to turn these bytes into text and back.
