### ISSUE TITLE
Reporting a security issue

### ISSUE THREAD

**Issue by randombit** [dedis/kyber#362]
I noticed something that may be a security issue. There is nothing in the readme to indicate how to report such things. Should I do so in this issue?

**Comment by kc1212** [comment]
You can email us directly. The lead engineer is @jeffallen and his address is jeff.allen@epfl.ch. If you prefer to encrypt emails then I'll let Jeff get back to you on his GPG key.

**Comment by jeffallen** [comment]
The security reporting address for Kyber is dedis-security@epfl.ch, and it will be documented in the next version's README and godoc. Thank you for the reminder.
