### ISSUE TITLE
XOF streams vs crypto/cipher

### ISSUE THREAD

**Issue by eliquious** [dedis/kyber#366]
Can someone outline the dis/advantages of using the Kyber XOF streams (blake2b/blake2s/keccak) instead of the ones included in `crypto/cipher`? Or when one might be better than the other?

**Comment by jeffallen** [comment]
The following three types are approximately the same:
* https://godoc.org/go.dedis.ch/kyber#XOF
* https://godoc.org/golang.org/x/crypto/blake2b#XOF
* https://godoc.org/golang.org/x/crypto/sha3#ShakeHash

The main difference is that kyber defines Reseed, which gives you a standard technique to change an Xof that is in read mode back into writable mode.

(I am closing this, but if you have more questions, feel free to re-open.)

**Comment by eliquious** [comment]
Thanks!

What about for stream ciphers? I'm looking specifically at the `cipher.Stream` interface. I see that Blake2/Keccak both implement the `XORKeyStream` method.

So why would you choose to use Kyber's blake2/keccak streams instead of the AES-based stream ciphers (like CFB/CTR/OFB) that are in `crypto/cipher`?

**Comment by kc1212** [comment]
In my opinion the difference is not significant. Maybe there are some performance differences but we haven't done any benchmarks.

With that said, regardless of whether you're using an AES-based or keccak-based stream cipher to encrypt something, you need to do authentication. For keccak there are schemes like https://keccak.team/ketje.html and https://keccak.team/keyak.html, for AES there's GCM. So don't use CFB/CTR/OFB without authentication.
