### ISSUE TITLE
Embedding on bn256

### ISSUE THREAD

**Issue by taybart** [dedis/kyber#367]
Hello, I am trying to embed data on bn256. I saw the note in that function. 
```
// XXX: An approach to implement this is:
// - Encode data as the x-coordinate of a point on y²=x³+3 where len(data)
//   is stored in the least significant byte of x and the rest is being
//   filled with random values, i.e., x = rand || data || len(data).
// - Use the Tonelli-Shanks algorithm to compute the y-coordinate.
// - Convert the new point to Jacobian coordinates and set it as p.

```

Does anyone have a more detailed explanation of how data was to be stored  as the x value? Does this mean that `EmbedLen` also needs to be implimented? I assume that embedding would be (forgive my pseudo-code/go hybrid)

```go
// G1
var x big.Int
for x != point.AtInfinity() {
  x = [rand(EmbedLen()-len(data)-1)..., data, len(data)]
}
p := curveOrder()
// x³+3
tmp := new(big.Int).Exp(x, 3, p)
tmp.Add(tmp, 3)

// TS
y := new(big.Int).ModSqrt(tmp, p)
residue := new(big.Int).Sub(p, y)

return x, y
```
Does any of that look ok? Or am I very confused (most likely). Not sure what to do about the quadratic residue though. I would love any guidance on doing this.

**Comment by jeffallen** [comment]
I'm hoping that @Daeinar can comment, as he's got the deepest background knowledge on how point embedding could/should work in pairing groups.

**Comment by nikkolasg** [comment]
@taybart I think you should have a look at how it is done for [ed25519](https://github.com/dedis/kyber/blob/master/group/edwards25519/point.go#L114). That will most likely answer your question because you could implement exactly the same process, and if not, feel free to post a follow up question here :)

**Comment by taybart** [comment]
@nikkolasg Thank you! I will look at that!

**Comment by taybart** [comment]
@nikkolasg Thank you! I assume that ge and fe have the same algos involved? Just different parameters? I see GF in there, I thought elliptic curve fields were different from Galios Fields? I have a couple of questions, I can move the discussions somewhere else? I only need a few pointers on some fine details here

**Comment by jeffallen** [comment]
Here is fine, or: https://github.com/dedis/cothority#contact

**Comment by taybart** [comment]
OK, I have added embedding on G1. This leads to issues with group operations though. After I embed, all of the prime field group operations don't work (Using the Elgamal example from ed25519). Do I have to use the quadratic extension field (G2 / gfp2) to embed information?

**Comment by taybart** [comment]
BTW this is the change: https://github.com/taybart/kyber/blob/master/pairing/bn256/point.go#L95

**Comment by taybart** [comment]
I fixed the Group functions (there was an issue with point marshaling in the Data function). I can make a pr, however, I did change the adapter (https://github.com/taybart/kyber/blob/master/pairing/adapter.go#L29). I will move this discussion to #383
