### ISSUE TITLE
BLS signature size

### ISSUE THREAD

**Issue by blockcodemagic** [dedis/kyber#375]
I am not a crypto expert. I see some BLS signature size over BN256 is 256bits. And kyber produces 512 bit signature. Is there a way we can get 256 bits signature?

**Comment by Gilthoniel** [comment]
For the explanation, we're marshaling x and y and each point requires 256 bits.

It's possible to get a signature of 256 bits if you marshal only the x coordinate and find y when unmarshaling but the curve is `y²=x³+3` which means you'll have two solutions and then you need to decide if you always the positive or the negative one.

**Comment by Gilthoniel** [comment]
The [Tonelli-Shanks algorithm](https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/Tonelli%E2%80%93Shanks_algorithm.html) could be used to find `y`. Unfortunately this would be backward incompatible and we won't be doing it.
