### ISSUE TITLE
kyber packaging - can't update multiple folder

### ISSUE THREAD

**Issue by nikkolasg** [dedis/kyber#376]
Hi,

I'm trying to merge the fork I made of kyber for drand with the latest kyber changes. I'm running into issues with respect to the packaging.

On `kyber:master`, now the imports are like the following:
```go
"go.dedis.ch/kyber/v3/share"
vss "go.dedis.ch/kyber/v3/share/vss/pedersen"
"go.dedis.ch/kyber/v3/sign/schnorr"
```
**Problem**: When I'm making a change on `share/vss/pedersen/vss.go`, it is not "seen" by Go, since it's not yet updated to the `go.dedis.ch/kyber/v3` repo. 

How can I change portions of code in multiple repos at once ? Is that even possible ... ? I'm not sure how can I merge back my changes on the DKG part if it is not possible. Any ideas ? The only possiblity that I see is to change the import to the regular name as before `github.com/dedis/share/vss/pedersen`.

I never used go modules yet, but is there a reason why `kyber` imports a specific version `go.dedis.ch/kyber/v3`, while *it is already* specified in the `go.mod` file (`module go.dedis.ch/kyber/v3`) ?  This method of packaging seems like the equivalent of treating each folder as a separate repo now...

IIRC (cc'd @ineiti), we had exactly the same problem using `gopkg` a while back, and at the time, had quite a lot of trouble with it...

**Comment by kc1212** [comment]
To update multiple modules, I use `replace` https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive

I don't fully understand your second question. If not mistaken, if you change something in one package then the change should appear in another package, as long as these two packages are in the same module.

**Comment by nikkolasg** [comment]
Thanks, after a few trials it worked !

> I don't fully understand your second question. If not mistaken, if you change something in one package then the change should appear in another package, as long as these two packages are in the same module.

By importing things like `go.dedis.ch/kyber/v3/share/vss/pedersen/` from the dkg package (instead of the regular `go.dedis.ch/kyber/share/vss/pedersen`), aren't you treating the vss package as a separate module, instead of another package ? In other words, isn't it possible to get a version X of VSS and a version Y of DKG in this setting ? At the moment, I have the impression it's like that, hence the need to use the `replace` command. If yes, that might be very troublesome, since both packages are quite linked together and X and Y might be two incompatible versions, as I just had. 

Anyway, you all have probably more experience with `go mod` than me, so I'll stop here ;) 

Thanks again.
