### ISSUE TITLE
[cosi] Collective public key A generation differ from the ietf draft

### ISSUE THREAD

**Issue by cedricfung** [dedis/kyber#387]
For an M of N signature, in the draft https://tools.ietf.org/id/draft-ford-cfrg-cosi-00.html, A is generated from the public keys of participants N.

But in the code, the AggregatePublic only includes members of M. https://github.com/dedis/kyber/blob/1a3d86c4f61cd7ac92bf14509aa887c728a5fe2a/sign/cosi/cosi.go#L306

**Comment by cedricfung** [comment]
Actually in the Challenge phase of the test code, H(V,A,M), the masks[i].AggregatePublic should be all the keys in N instead of M. https://github.com/dedis/kyber/blob/1a3d86c4f61cd7ac92bf14509aa887c728a5fe2a/sign/cosi/cosi_test.go#L86

**Comment by cedricfung** [comment]
Also in the verification method, H(V,A,M) uses mask.AggregatePublic as the A

https://github.com/dedis/kyber/blob/1a3d86c4f61cd7ac92bf14509aa887c728a5fe2a/sign/cosi/cosi.go#L196

**Comment by cedricfung** [comment]
And in the draft https://tools.ietf.org/id/draft-ford-cfrg-cosi-00.html#signature-verification

```
SHA512(R || A || S)
A' = A - T
[8][s]B = [8]R + [8][c]A'
```

**Comment by jeffallen** [comment]
The draft is expired, and we are not currently working on standardising CoSi.

Closing this issue now, but if I've misunderstood and you are reporting a problem with the implementation itself, please re-open and explain what it does, what you think it should do, and why the difference is important. Thanks.
