### ISSUE TITLE
Error loading module requirements

### ISSUE THREAD

**Issue by youssefnotes** [dedis/kyber#389]
I get the following error when running the dh_test code as a module
```
go: finding golang.org/x/crypto/blake2b latest
go: finding golang.org/x/crypto latest
go: github.com/dedis/fixbuf@v1.0.3: parsing go.mod: unexpected module path "go.dedis.ch/fixbuf"
go: error loading module requirements
```
link to the code [https://github.com/youssefnotes/dh](url)
thanks for help

**Comment by ineiti** [comment]
You're mixing `gopkg.in` and go-modules in your project. Use one of:
- `gopkg.in/dedis/kyber.v3` with GO111MODULE=off
- `go.dedis.ch/kyber/v3` with GO111MODULE=on

**Comment by youssefnotes** [comment]
Thanks
