### ISSUE TITLE
go.dedis.ch appears to be down

### ISSUE THREAD

**Issue by se3000** [dedis/kyber#392]
We can't download dependencies on CI.

Happy to open a PR to switch the URL in go.mod, unless you'd rather fix the site.

In the meantime, setting `GOPROXY=https://proxy.golang.org` appears to fix the issue.

**Comment by ineiti** [comment]
same here - in fact the whole dedis.ch nameserver seems to be down... even dedis.ch doesn't resolve.

**Comment by jeffallen** [comment]
The domain expired, and we are getting it fixed. This is related to dedis/protobuf#67, which I already had on my todo list for ASAP, but is apparently even more urgent.

**Comment by jeffallen** [comment]
reopened until the domain is working again...
