### ISSUE TITLE
Dependency has a GPL license, invalidating the MPL?

### ISSUE THREAD

**Issue by tobowers** [dedis/kyber#403]
Hello! I created an issue in fixbuf ( https://github.com/dedis/fixbuf/issues/4 ). It looks like that dependency would invalidate the MPL in this library?

**Comment by ineiti** [comment]
Thanks - I created a PR here: dedis/fixbuf#5.

**Comment by jeffallen** [comment]
Fixed in dedis/fixbuf#5.
