### ISSUE TITLE
Arithmetic Issue

### ISSUE THREAD

**Issue by lhmerino** [dedis/kyber#414]
https://github.com/dedis/kyber/blob/52437c55c7e6e1785c4d74e0304dd5ed100fd6c5/group/edwards25519/point.go#L111

On this line, (255 - 8 - 8)/8 = 29.875 and returns 29 when it should return 30 given the documentation of this function (1 byte for length and 1 byte for randomness) and a point is 32 bytes. Instead this line should be (256 - 8 - 8) / 8.

**Comment by ineiti** [comment]
As far as I know, the points are defined over the field modulo `P`, which for ed25519 is `2**255-19`. So there are only the bits 0-254 available, so 255 in total. So the formula is correct.

Rounding down is the correct thing to do here, as we don't want to store partial bytes. Theoretically you could store 7 more bits, but we're not bit-picking here...

I'm an engineer, but working with these curves for nearly 5 years now. So I'm pretty sure what I write is correct - but I'm happy to learn that I still do not understand these curves more completely ;)

**Comment by lhmerino** [comment]
Ah ok, this makes sense. The reason that I thought it was 256 instead of 255 was because the documentation said it needed one byte for length and one byte for randomness and a curve point was 32 bytes so it didn't make sense to me... Your post made me realize that I forgot about the prime modulus which is 2**255.
