### ISSUE TITLE
Can't make orderer-docker

### ISSUE THREAD

**Issue by Tallminsome** [dedis/kyber#420]
## Basic Description
I was using the packeage go.dedis.ch in my own consensus,when I was about to remake the orderer-docker.The error:
'orderer/consensus/tspbft/message/buffer.go:5:2: cannot find package "go.dedis.ch/kyber/pairing" in any of:
/opt/gopath/src/github.com/hyperledger/fabric/vendor/go.dedis.ch/kyber/pairing (vendor tree)
/opt/go/src/go.dedis.ch/kyber/pairing (from $GOROOT)
/opt/gopath/src/go.dedis.ch/kyber/pairing (from $GOPATH)
'comes out.
Then I checked my go env, I found my GOROOT AND GOPATH is not what it reported.It's:
GOROOT="/usr/local/go"
GOPATH="/home/george/go"
Later, I tried to put the pkg to where it reported, it still doesn't work out.
## Environment 
Ubuntu 16.0.4 
Hyperledger Fabric 1.4.4 
Golang 1.14.2
## How to repeat the problem
make orderer-docker
## What I‘ve already tried
Put the pkg to where it reported

**Comment by ineiti** [comment]
If I understand correctly, `orderer` comes from your package, correct? Then your import seems to be wrong. `go.dedis.ch/kyber/pairing` should be `go.dedis.ch/kyber/v3/pairing`, no?

**Comment by ineiti** [comment]
also, the `repeat the problem` is difficult for me, if I don't have access to your code... You would need to provide more context.

**Comment by Tallminsome** [comment]
Thanks @ineiti .
When the first time I import this pkg, there was '/v3' in it,but then I checked the pkg.I found there actually didn't exist 'v3' file, so I delete it.I will try your advise later, cuz I am busy with my paper.Thanks a lot!!!

**Comment by ineiti** [comment]
https://github.com/golang/go/wiki/Modules#version-selection

**Comment by jeffallen** [comment]
This seems to be resolved.
