### ISSUE TITLE
Using Pedersen DKG with Docker

### ISSUE THREAD

**Issue by mthienpont** [dedis/kyber#429]
Hello,

Thank you all for this excellent library; it is serving me well for a personal project I am working on!

I am implementing the Pedersen DKG algorithm as demonstrated in `examples/dkg_test.go` with each node residing on its own Docker container. In my attempt to use gRPC to send across _public keys_, _deals_ and _responses_, I am having trouble converting the appropriate structs into proto definitions - I have tried manually nesting proto messages and using the `go.dedis.ch/protobuf` library to generate a proto definition, to no avail...

Is there a method of achieving this I am overlooking? Any help would be hugely appreciated.

**Comment by ineiti** [comment]
Hi,

great you're having fun with the library. We're using the `go.dedis.ch/protobuf` internally, but it's definitely not the best tool, and your attempt to use `gRPC` is very good!

What you'll have to do is to fill the gRPC structure manually with the values from the `deals` and `responses`. This is how `drand` does it: https://github.com/drand/drand/blob/a6e4c31c827990ed876bfab3f67ae8b332b078d5/core/convert.go#L50

For the `public keys`, you can use the `MarshalBinary` and `UnmarshalBinary` to convert them to/from a slice of bytes and put it in the `gRPC` structure.

Hope this helps...

**Comment by mthienpont** [comment]
Sweet advice and link. Managed to get it working for public keys and deals so far!
Thank you kindly :)
