### ISSUE TITLE
Group Membership Checking

### ISSUE THREAD

**Issue by prosticoco** [dedis/kyber#445]
Hello,
I would like to use this library to implement multiple OT-related protocols. I intend to use various groups in my protocols, however many protocols require checking group membership of points received by the parties in order to ensure security. Is there any kind of method I can use on Group interfaces to do this checking (or any way this is feasible when using curveEd25519 for example)?

Many thanks in advance,

Adrien

**Comment by ineiti** [comment]
Here is how the `Embed` method checks if a point is on the curve or not:

https://github.com/dedis/kyber/blob/master/group/edwards25519/point.go#L157

**Comment by prosticoco** [comment]
Perfect thanks!

**Comment by prosticoco** [comment]
Then is there a way to do so generically for any group, as in this case this only checks it for the edwards curve. In this case I would need to have access to the order of the group from the group interface.

**Comment by ineiti** [comment]
True - we've been discussing this some years ago to know whether we want to get the configuration from the groups in the `Group` interface or not. In the end we decided not to...

**Comment by prosticoco** [comment]
Okay no problem, I realized the Unmarshalling function on points does some checking as well, if I really need something more generic in the end I will fork it then. Thanks for the responses

**Comment by jeffallen** [comment]
This seems to be done. Thanks @ineiti .

**Comment by pierluca** [comment]
This seems to have been addressed, closing the issue.
