### ISSUE TITLE
Investigate bringing in optimisations in from cloudflare/bn256

### ISSUE THREAD

**Issue by jeffallen** [dedis/kyber#446]
This is a tracking issue to remind us to watch cloudflare/bn256#23 and bring those changes into Kyber and possibly make use of them if possible.

They are vartime, so we need to consider if we can safely use them.

**Comment by jeffallen** [comment]
See also #440, which is another vartime issue.

**Comment by AnomalRoil** [comment]
@Robingoumaz

**Comment by pierluca** [comment]
Done in #518
