### ISSUE TITLE
Misleading comment on the "hashToPoint()" function

### ISSUE THREAD

**Issue by kubasiemion** [dedis/kyber#450]
File kyber/pairing/bn256/point.go /, lines 224-225
A simple quid-pro-quo, but we should have mercy on the people trying to follow the algorithms:
`// hashes a byte slice into two points on a curve represented by big.Int`
`// ideally we want to do this using gfP, but gfP doesn't have a ModSqrt function`
`func hashToPoint(m []byte) (*big.Int, *big.Int) {...}`

Should be: "hashes into a point represented by two big.Int's"

**Comment by ineiti** [comment]
Thanks for the comment. Github makes it now really easy to propose changes to the files. So please feel free to open a PR against `bn256/point.go`.
