### ISSUE TITLE
How to transmit shares over the network?

### ISSUE THREAD

**Issue by zeminzhou** [dedis/kyber#451]
Hi guys

I encountered some problems when using share packages. I refer to the dkg_test.go file in the examples directory and encrypt the data to get K, C and n private keys. I want to encode K, C and n private keys with the help of encoding/json and transmit them through the network, but it fails.

Can you give me some suggestions on how to transfer K, C, suite and n private keys through the network?

**Comment by ineiti** [comment]
Thanks for the question. Here some answers:

- you don't transfer the Suite over the network - this one is static and must be chose beforehand. So you just initialise it on the sender and the receiver end with your preferred suite
- There are `MarshalBinary` and `UnmarshalBinary` methods on `Point` and `Scalar`. You should use those to convert from/to binary

**Comment by zeminzhou** [comment]
Think your answer

**Comment by zeminzhou** [comment]
> Thanks for the question. Here some answers:
> 
>     * you don't transfer the Suite over the network - this one is static and must be chose beforehand. So you just initialise it on the sender and the receiver end with your preferred suite
> 
>     * There are `MarshalBinary` and `UnmarshalBinary` methods on `Point` and `Scalar`. You should use those to convert from/to binary

Sorry to disturb you again, I performed the following code based on your opinion, but the operation failed:
`type PriShareByte struct {                                                          
    shareI int                                                                      
    shareV []byte                                                                   
}

psb := PriShareByte{}
// ps is a share.PriShare variable 
psb.shareI = ps.I
psb.sharev = ps.V.MarshalBinary()

ps1 := share.PriShare{}
ps1.I = psb.shareI
ps1.V.UnmarshalBinary(psb.shareV) // an error happen here: panic: runtime error: invalid memory address or nil pointer dereference
`
Where did I go wrong？

**Comment by zeminzhou** [comment]
Hi guy, if I generate n private keys and send keys to n personals, then n personals send himself private key to others. When one of them receives someone else's private key, how does he verify that the private key is correct?

**Comment by ineiti** [comment]
Of course you should never send your private keys to somebody else - so I guess that's a misunderstanding of the `Point` and `Scalar`s here.

Usually when you receive for example a `Deal`, then this structure will be verified by the receiver, which makes sure that all structures in there are correct and that the node is not proposing a wrong deal.

Bot for more details you'll have to read the paper - I'm not very familiar with it.
