### ISSUE TITLE
How to run tbls over network?

### ISSUE THREAD

**Issue by zhazhalaila** [dedis/kyber#454]
Hi guys

I encountered some problems when using tbls packages. I have four nodes and one client. I generated a public key and four private keys using the tbls model on the client. How do I pass these four private keys and public key to the other four nodes through the network(These codes are only used for testing and will not be placed in the production environment.)?Or is there a way to write these private and public keys into a file, and then let the node read these files?

**Comment by ineiti** [comment]
Hi there,

from what the documentation of tbls says, you should create the private keys with a distributed key generation algorithm. As it doesn't make a lot of sense to send private keys over the network...

For simulations you can of course create these keys, and then use the `encoding.BinaryMarshaler` to write/read to/from a file.
