### ISSUE TITLE
Old dkg nodes doesn't certify after re-sharing 

### ISSUE THREAD

**Issue by Mahsa-Bastankhah** [dedis/kyber#469]
I added a new test to [dkg_test ](https://github.com/Mahsa-Bastankhah/kyber/blob/c3e2b5b7c6a3f6423bf03c3ec85e5f4c859cfc44/share/dkg/pedersen/dkg_test.go#L1339)in the PR #468. In this test I create a set of dkg nodes and did the initial dkg setup for them then I create a new set of dkg nodes to reshare the secret of the old nodes among the new dkg nodes. There is one common node between the old committee and the new committee(`oldDkgs[4]` , `newDkgs[0]`). The test is essentially the same as [this already existing test](https://github.com/Mahsa-Bastankhah/kyber/blob/c3e2b5b7c6a3f6423bf03c3ec85e5f4c859cfc44/share/dkg/pedersen/dkg_test.go#L901) except that it calls `dkg.Certified()` in the end to make sure that all the nodes certify the resharing. Surprisingly all the nodes of the old committee except for the one that is common between the new and the old committee fail in certifying. The new committee nodes however successfully certify. And even more surprising is that when I remove the common node the certify is successful for all the old and new dkg nodes so apparently the one common node is causing the problem. I tried to track the problem  to find its source. This is what I found out:
In resharing protocol old nodes are supposed to create a deal for each new node. [In line](https://github.com/Mahsa-Bastankhah/kyber/blob/c3e2b5b7c6a3f6423bf03c3ec85e5f4c859cfc44/share/dkg/pedersen/dkg_test.go#L1420) `oldDkgs[4]` creates one deal less than the other old nodes. In fact since `oldDkgs[4]` and `newDkgs[0]` are the same, `oldDkgs[4]` only creates deals for `newDkgs[1:5]`. Later in resharing protocol new nodes after receiving the deals create a respond and broadcast this response but `newDkgs[0]` never broadcast its respond to the deal received from  `oldDkgs[4]` to the other old dkg nodes. In fact, [line](https://github.com/Mahsa-Bastankhah/kyber/blob/c3e2b5b7c6a3f6423bf03c3ec85e5f4c859cfc44/share/dkg/pedersen/dkg_test.go#L1420) implicitly adds this respond to the respond sets of `newDkgs[0]` and later [in line](https://github.com/Mahsa-Bastankhah/kyber/blob/c3e2b5b7c6a3f6423bf03c3ec85e5f4c859cfc44/share/dkg/pedersen/dkg_test.go#L1439) this respond is implicitly added to the response set of `newDkgs[1:5]` but this single response is never added to the respond set of the old committee members. Each node has `oldN` aggregators/verifiers and each of them should have `newN` responses however [in line](https://github.com/Mahsa-Bastankhah/kyber/blob/b8734881a60b55845eda692c35a109a77ffdd527/share/dkg/pedersen/dkg_test.go#L1508) I am printing the number of responses that the old nodes receive and you can observe that they miss one response. In another word old nodes are not receiving the response that `newDkgs[0]` creates in respond to the deal that `oldDkgs[4]` builds.

**Comment by nkcr** [comment]
Thank you for pointing that out. Indeed, if we print the missing responses from oldDkgs aggregators we can see that aggregator 4 is always missing response from the dkg `1`:

```
oldDkg 0: agg[2] -> []	agg[3] -> []	agg[4] -> [0]	agg[0] -> []	agg[1] -> []	
oldDkg 1: agg[3] -> []	agg[4] -> [0]	agg[0] -> []	agg[1] -> []	agg[2] -> []	
oldDkg 2: agg[4] -> [0]	agg[0] -> []	agg[1] -> []	agg[2] -> []	agg[3] -> []	
oldDkg 3: agg[2] -> []	agg[3] -> []	agg[4] -> [0]	agg[0] -> []	agg[1] -> []	
oldDkg 4: 
```

```go
	for _, dkg := range oldDkgs {
		fmt.Printf("oldDkg %d: ", dkg.oidx)
		for j, aggr := range dkg.oldAggregators {
			fmt.Printf("agg[%d] -> %v\t", j, aggr.MissingResponses())
		}
		fmt.Println()
	}
```

which makes the certification fail: in https://github.com/dedis/kyber/blob/c69494d742d8c77d0aa6efc09e60e61a3ea10380/share/vss/pedersen/vss.go#L688.
