### ISSUE TITLE
found a bug in dkg_test

### ISSUE THREAD

**Issue by Mahsa-Bastankhah** [dedis/kyber#470]
I added an additional condition to [line](https://github.com/Mahsa-Bastankhah/kyber/blob/b8734881a60b55845eda692c35a109a77ffdd527/share/dkg/pedersen/dkg_test.go#L1019) because the [previous version](https://github.com/dedis/kyber/blob/c69494d742d8c77d0aa6efc09e60e61a3ea10380/share/dkg/pedersen/dkg_test.go#L1019) was ignoring sending responses to some old nodes that it is not supposed to ignore. This `if` branch should be only triggered for nodes in common between the old and new committee but apparently `dkg.nidx` for some old nodes has some arbitrary values and this activates the branch so I added one more condition to make sure that this branch is only triggered for the last old dkg node which is part of the new dkg as well.

**Comment by pierluca** [comment]
This was addressed as part of #471 . Thank you !
