### ISSUE TITLE
DKG Protocol - Public Key Change After Reshare

### ISSUE THREAD

**Issue by leetingo** [dedis/kyber#489]
## DKG Protocol - Public Key Change After Reshare

**Description:**

I am currently working with the DKG protocol for threshold encryption and decryption as provided under the `share/dkg/pedersen` folder. 

While exploring the capabilities of the protocol, I've noticed that the DKG supports resharing of secrets, which is a helpful feature. However, it appears that the public key changes post-reshare, which is causing current threshold encryption fail in my application.

**Expected Behavior:**

Ideally, I would expect that the public key remains constant after the reshare operation. 

**Actual Behavior:**

Currently, the public key changes each time a reshare is performed.

**Steps to Reproduce:**

1. Initialize the DKG protocol
2. Perform the reshare operation
3. Observe the change in the public key

**Additional Information:**

If it is by design that the public key changes after a reshare, could you please explain the reasoning behind this? If there's a way to maintain the same public key post-reshare, I'd appreciate if you could guide me on how to do it. I noticed that checking public key remains the same is mentioned in https://github.com/dedis/kyber/blob/a008b2d45c5c8675d2f01d140b7232166757a013/share/dkg/pedersen/dkg_test.go#L657, but it is not implemented in the relevant code.

Looking forward to your support on this issue. 

Thank you in advance!

**Comment by ineiti** [comment]
Can you please give a short code snippet that shows this behaviour? I think you're right that the public key should stay the same, but I'm not sure we're talking about the same public key...

**Comment by TingoLee** [comment]
I have added a test at the end of `TestDKGResharing` funtion in `dkg_test.go` to verify whether the old public key and the new public key are the same. I'm not sure if I'm doing it right. My app use this public key to encrypt messages and the threshold encryption/decryption works fine.

Here is the relevant code snippet from the test:

`// 3.
for i := 0; i < len(dkgs); i++ {
	require.Equal(t, shares[i].Public(), newShares[i].Public())
}`

**Comment by ineiti** [comment]
I'll have a look into it tomorrow, but it seems you're comparing the public keys of the different nodes, which of course will be different after resharing, because that's the point of it.

You might want to look if there is some `Aggregate` key or so and compare that, which should be the same before and after resharing.

**Comment by TingoLee** [comment]
I reviewed the dkg code again, and what I should be checking is whether the public key of each node has changed before and after resharing. According to the code comments, the public polynomial should be different after resharing, but the first coefficient of the public polynomial (which is the dkg public key) should remain unchanged.

**Comment by ineiti** [comment]
Can you test whether this one stays constant after resharing?

https://github.com/dedis/kyber/blob/a008b2d45c5c8675d2f01d140b7232166757a013/share/dkg/pedersen/structs.go#L24

That's what I think must not change between resharing. Also, you could test that the following doesn't change, but this is already done in the tests:

https://github.com/dedis/kyber/blob/master/share/vss/pedersen/vss.go#L481

In a real-world implementation you should never have access to the other shares, so you will not be able to do the `RecoverSecret`. But you should always be able to do the `func (d *DistKeyShare) Public() kyber.Point`.

I hope that helps.

**Comment by TingoLee** [comment]
This is exactly what I am testing. In the test function, all the DistKeyShares generated by every node are stored in the 'shares' slice, and the DistKeyShares after resharing are stored in the 'newShares' slice. Therefore, I tested whether the Public is the same before and after resharing.

**Comment by ineiti** [comment]
And the tests pass? So all is well now?

**Comment by K1li4nL** [comment]
As far as I understand, this check is now present, it was introduced in https://github.com/dedis/kyber/pull/512 as we swapped our pedersen dkg implementation with the one from DRAND. Thank you for you work @leetingo ! I believe this issue as well as #491 can be closed.

https://github.com/dedis/kyber/blob/b172e02f7ce590f74d69baef55d5172273d1d1b7/share/dkg/pedersen/dkg_test.go#L117-L128
