### ISSUE TITLE
v3/sign/bls shows up as depreciated when i try to import it

### ISSUE THREAD

**Issue by aludayalu** [dedis/kyber#511]
I was trying to use the v3/sign/bls library but vscode is giving me this error as whenever i import "go.dedis.ch/kyber/v3/sign/bls".

Error:

```
"go.dedis.ch/kyber/v3/sign/bls" is deprecated: This version is vulnerable to rogue public-key attack and the new version of the protocol should be used to make sure a signature aggregate cannot be verified by a forged key. You can find the protocol in kyber/sign/bdn. Note that only the aggregation is broken against the attack and a later version will merge bls and asmbls.deprecated(default)
```

<img width="801" alt="Screenshot 2024-04-26 at 1 04 58 AM" src="https://github.com/dedis/kyber/assets/97356263/0721cef8-0ba6-4551-b1d4-ead72ace3ec7">

I wanted to deploy this library for a production codebase and would want to make sure that I am not using a depreciated library.

**Comment by CluEleSsUK** [comment]
As far as I understand you could avoid this by ensuring users commit to their public key (eg by signing with it) before aggregation

**Comment by aludayalu** [comment]
No I wont be able to do that as that would waste a lot of network bandwidth cuz lot of signatures would be needed to be sent over network.

**Comment by CluEleSsUK** [comment]
Alternatively they could by sending a hash of the public key. Less bandwidth, but still would still require some network interaction

**Comment by ineiti** [comment]
Why not use the bdn-version of the protocol?

> // Package bdn implements the Boneh-Drijvers-Neven signature scheme which is
> // an implementation of the bls package which is robust against rogue public-key attacks. Those
> // attacks could allow an attacker to forge a public-key and then make a verifiable
> // signature for an aggregation of signatures. It fixes the situation by
> // adding coefficients to the aggregate.

Also - if the attacker knows the public key, they can also send a hash of it, no? :)

**Comment by CluEleSsUK** [comment]
Ah my intention was a hash of the public key early in the protocol before others shared their keys, but perhaps I’m missing an attack vector!

**Comment by aludayalu** [comment]
What is the bdn package? Also do you know about any cryptographic libraries which have good documented bls support? @ineiti

**Comment by aludayalu** [comment]
@ineiti @CluEleSsUK The solution would be to sign a pseudo randomly generated message and everyone on the network validates it. If the validation was successful then everyone would mark that public key as a verified public key in their local database. From the next time whenever the key is introduced onto the network, the network would not have to verify whether the public key is a forged one or not.

**Comment by ineiti** [comment]
@aludayalu I'm referring to the comment at the top of the bls package, which refers to this:

https://github.com/dedis/kyber/blob/master/sign/bdn/bdn.go

And, again, please be careful if you use kyber in production software.

**Comment by pierluca** [comment]
I believe this has been addressed. Closing the issue now.
