### ISSUE TITLE
Secret Sharing and Schnorr Signature Tweaks

### ISSUE THREAD

**Issue by Daeinar** [dedis/kyber#65]
- `VerifySchnorrSig` [1] should be changed so that it can be used "offline" after the JVSS group (and thus the Schnorr struct) has vanished.
- Creation of Schnorr signatures in JVSS (r = v + cx) [2] and CoSi (r = v - cx) should be unified.
- `NewReceiver` [3] does not need the `suite` as a parameter because it's already stored in `*config.KeyPair`

[1] https://github.com/dedis/crypto/blob/master/poly/schnorr.go#L245
[2] https://github.com/dedis/crypto/blob/master/poly/schnorr.go#L177
[3] https://github.com/dedis/crypto/blob/master/poly/joint.go#L72

**Comment by nikkolasg** [comment]
Doing the refactoring of the distributed schnorr signature, I'm going for the `r = v + cx` approach as it's similar to EdDSA,i.ee compatible. I'm also taking care of 1).

**Comment by nikkolasg** [comment]
Point 1) and 3) are related to the old sharing code. The new code in `share/` takes care of all 3 points.
