### ISSUE TITLE
TestAES in sha3 package fails (sometimes)

### ISSUE THREAD

**Issue by Liamsi** [dedis/kyber#85]
Just stumbled upon this twice today. To reproduce run the tests in `github.com/dedis/crypto/cipher/sha3` until you see (using some loop provided by your favourite shell):

```
--- FAIL: TestAES (0.00s)
        cipher.go:183: Encryptions not sufficiently different 0.28125
FAIL
FAIL    github.com/dedis/crypto/cipher/sha3     0.115s
```

(Maybe be related to issue #70?)

**Comment by Liamsi** [comment]
As discussed with @Daeinar this most probably isn't a bug in the implementation but rather in the tests which check for a certain distance of the produced encrypted messages (see https://github.com/dedis/crypto/blob/master/test/cipher.go#L250) which on is reached often and sometimes not.

**Comment by ineiti** [comment]
So can you make a loop and only fail if the distance is smaller a threshold number of times?

**Comment by Liamsi** [comment]
> So can you make a loop and only fail if the distance is smaller a threshold number of times?

@bford proposed to lower the "delta" (which at the moment is 0.3)

**Comment by jeffallen** [comment]
I managed to make this happen once today by raising n to 50 in CipherTest. When I set it to 100 and removed FailNow, I got a failure rates as high as 8%.

**Comment by nikkolasg** [comment]
Is it possible as @Liamsi wrote to just "lower the delta" so this test passes more often ? I'm not 100% fond of statisticals tests but if it's there we should probably try to keep it but make it pass...
