### ISSUE TITLE
[Refactoring] Secret Sharing

### ISSUE THREAD

**Issue by Daeinar** [dedis/kyber#96]
This will address (at least) the following issues:

- Deletion of the entire secret sharing code base found in `dedis/crypto/poly`
- New framework for secret sharing now in `dedis/crypto/share`
  + Rewrite the core of the library for polynomials
  + Integration of *public verifiable secret sharing* found in [randhound](https://github.com/dedis/cothority/blob/master/randhound/proof.go)
  + Rewrite of the old `poly/deal.go` into `share/vss.go`
  + Rewrite of the `poly/joint.go` and `poly/schnorr.go`
  + Adapt/rename the (JVSS)[https://github.com/dedis/cothority/tree/master/jvss]
  
By side effect, this will also include
  + `sign` package to pave the way for later bigger restructuring. It will include a basic `Schnorr` signature.
  + `DLEQ` (discrete log equality) functionality into the `proof` package

**Comment by nikkolasg** [comment]
After some trials and errors, I intend to propose the different PRs such as:
 1. add `sign/schnorr{_test}.go` in `refactoring_sign` merging against master
 2. add `proof/dleq.go` in `refactoring_dleq` mering against master
 3. add `share/vss{_test}.go` in `refactoring_share_vss` merging against master
 4. add `share/pvss{_test}.go` in `refactoring_share_pvss` merging against master
 5. add `share/vss{_test}.go` in `refactoring_share_vss` merging against master
 6. add `share/joint{_test}.go` in `refactoring_share_joint` merging against master
 7. add `share/schnorr{_test}.go` in `refactoring_share_schnorr` merging against master

**Comment by nikkolasg** [comment]
Done.
